#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oppo/camera

PRODUCT_COPY_FILES += \
    vendor/oppo/camera/proprietary/odm/etc/camera/stereoParams.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/stereoParams.bin \
    vendor/oppo/camera/proprietary/odm/etc/init/camerasloganserver.rc:$(TARGET_COPY_OUT_ODM)/etc/init/camerasloganserver.rc \
    vendor/oppo/camera/proprietary/vendor/etc/camera/Arc_wdc_calib.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/Arc_wdc_calib.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/M_Attribute_AG_BMW_1.1.0.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/M_Attribute_AG_BMW_1.1.0.model \
    vendor/oppo/camera/proprietary/vendor/etc/camera/M_Attribute_Gender_Age_1.0.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/M_Attribute_Gender_Age_1.0.model \
    vendor/oppo/camera/proprietary/vendor/etc/camera/engineer_camera_config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/engineer_camera_config \
    vendor/oppo/camera/proprietary/vendor/etc/camera/faceBeautyParam/fb_default:$(TARGET_COPY_OUT_VENDOR)/etc/camera/faceBeautyParam/fb_default \
    vendor/oppo/camera/proprietary/vendor/etc/camera/faceBeautyParam/fb_default_19661:$(TARGET_COPY_OUT_VENDOR)/etc/camera/faceBeautyParam/fb_default_19661 \
    vendor/oppo/camera/proprietary/vendor/etc/camera/faceBeautyParam/fb_default_20682:$(TARGET_COPY_OUT_VENDOR)/etc/camera/faceBeautyParam/fb_default_20682 \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/000.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/000.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/000_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/000_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/000_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/000_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/001.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/001.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/001_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/001_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/001_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/001_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/002.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/002.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/002_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/002_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/002_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/002_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/003.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/003.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/003_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/003_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/003_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/003_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/010.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/010.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/010_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/010_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/010_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/010_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/011.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/011.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/011_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/011_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/011_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/011_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/012.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/012.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/012_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/012_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/012_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/012_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/013.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/013.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/013_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/013_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/100.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/100.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/100_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/100_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/100_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/100_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/101.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/101.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/101_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/101_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/101_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/101_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/102.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/102.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/102_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/102_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/102_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/102_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/103.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/103.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/103_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/103_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/103_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/103_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/110.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/110.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/110_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/110_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/110_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/110_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/111.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/111.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/111_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/111_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/111_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/111_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/112.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/112.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/112_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/112_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/112_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/112_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/113.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/113.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/113_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/113_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/200.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/200.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/200_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/200_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/200_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/200_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/201.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/201.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/201_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/201_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/201_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/201_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/202.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/202.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/202_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/202_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/202_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/202_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/203.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/203.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/203_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/203_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/203_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/203_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/210.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/210.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/210_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/210_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/210_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/210_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/211.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/211.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/211_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/211_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/211_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/211_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/212.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/212.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/212_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/212_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/212_pre.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/212_pre.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/213.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/213.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/213_pre.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/213_pre.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreCalVarBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreCalVarBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreHighPassBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreHighPassBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreHoriFilterBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreHoriFilterBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreMakeupBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreMakeupBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreMorphBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreMorphBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreNoFaceBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreNoFaceBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreNormalBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreNormalBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreOnlywhitenBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreOnlywhitenBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreSkintuneBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreSkintuneBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreSurfaceBlurBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreSurfaceBlurBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/PreVertFilterBinary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/PreVertFilterBinary.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/eyeBright.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/eyeBright.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/skin_CCT.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/skin_CCT.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/skin_back.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/skin_back.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/skin_dark.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/skin_dark.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/skin_indian.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/skin_indian.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/skin_normal.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/skin_normal.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/skinmask.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/skinmask.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/fb_model/skinmask.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fb_model/skinmask.png \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/B1VLf4peM:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/B1VLf4peM \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/B1aMqioxf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/B1aMqioxf \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/B1nmcmWbG:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/B1nmcmWbG \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/B1si_XbZz:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/B1si_XbZz \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/BJJAwoigM:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/BJJAwoigM \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/BJyKIwqxz:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/BJyKIwqxz \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/ByW7g4bbf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/ByW7g4bbf \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/ByYo3If:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/ByYo3If \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/BycYf7WWz:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/BycYf7WWz \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/EyxRbD2UCe:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/EyxRbD2UCe \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/SJ3mbr6ef:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/SJ3mbr6ef \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/SkpZ8ebbz:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/SkpZ8ebbz \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/Sy4uLSTgf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/Sy4uLSTgf \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/Syt2KeZZf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/Syt2KeZZf \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/black_gold.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/black_gold.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/bowu-2.1.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/bowu-2.1.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/bright_coloured.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/bright_coloured.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/default:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/default \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/f_bin_hideaki:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/f_bin_hideaki \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/f_candy_water_weak.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/f_candy_water_weak.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/f_contrast_gray_face_dark:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/f_contrast_gray_face_dark \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/f_fuji_strong.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/f_fuji_strong.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/f_japan_strong.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/f_japan_strong.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/interstellar_space.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/interstellar_space.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/jiari-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/jiari-2.0.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/lvtu-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/lvtu-2.0.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/meiwei-2.2.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/meiwei-2.2.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/neon-2020.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/neon-2020.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_black_and_white:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_black_and_white \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_highlight:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_highlight \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_ins:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_ins \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_natal:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_natal \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_olympus:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_olympus \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_plain:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_plain \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_show:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_show \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_solar:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_solar \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_strong:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_strong \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/oppo_video_filter_west:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/oppo_video_filter_west \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/p4_1.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/p4_1.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/p4_2.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/p4_2.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/p4_3.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/p4_3.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/p4_4.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/p4_4.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/qiuri-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/qiuri-2.0.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/r1JaFSZZG:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/r1JaFSZZG \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/r1PrfoolG:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/r1PrfoolG \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/rJ5g5vPWG:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/rJ5g5vPWG \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/rJxJtmaez:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/rJxJtmaez \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/realme-black-gold-1.1-RGB.CUBE.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/realme-black-gold-1.1-RGB.CUBE.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/realme-cyberpunk-RGB.CUBE.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/realme-cyberpunk-RGB.CUBE.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/realme-infra-RGB.CUBE.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/realme-infra-RGB.CUBE.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/red-red.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/red-red.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/rkMhq4ZWf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/rkMhq4ZWf \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/rkx5u4Zbf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/rkx5u4Zbf \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/senlin-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/senlin-2.0.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/sky-blue.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/sky-blue.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/tree-green.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/tree-green.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/filters_lut/yuanqi-2.2s.cube.rgb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filters_lut/yuanqi-2.2s.cube.rgb.bin \
    vendor/oppo/camera/proprietary/vendor/etc/camera/gasryuv.model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gasryuv.model \
    vendor/oppo/camera/proprietary/vendor/etc/camera/license.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/license.lic \
    vendor/oppo/camera/proprietary/vendor/etc/camera/merged_model_post:$(TARGET_COPY_OUT_VENDOR)/etc/camera/merged_model_post

PRODUCT_PACKAGES += \
    libMegviiHumBokehPost-mtk \
    libVDDualCameraBlurless \
    libacdk \
    libaf6133 \
    libaf6133e \
    libmegface_rt_bokeh \
    libmmprofile \
    libvtclib \
    libvtclib_sala1008 \
    libvpuapi.mtk \
    vendor.mediatek.hardware.vpu@1.0 \
    vendor.oplus.hardware.camera.slogan@1.0-impl \
    libRbsFlow \
    libSonyIMX471RmscLibrary \
    libalipay_factory \
    libarcsoft_dualcam_wt_calibration \
    libarcsoft_dualcam_wt_verification \
    libcalibverifyW_T \
    libfasteningPlugin \
    libremosaic_wrapper \
    libremosaiclib \
    OppoCamera \
    vendor.oplus.hardware.camera.slogan@1.0 \
    coloros-support-wrapper \
    main-framework \
    main-services \
    oplus-framework \
    oplus-services \
    com.oppo.camera.unit.sdk \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    libccu_gc02k0_mipi_raw.ddr \
    libccu_gc02m0_mipi_mono.ddr \
    libccu_gc2375h_mipi_raw_19661.ddr \
    libccu_imx471_mipi_raw1.ddr \
    libccu_imx682_mipi_raw.ddr \
    libccu_ov02b10_mipi_raw.ddr \
    libccu_ov02b1b_mipi_mono.ddr \
    libccu_ov8856_mipi_raw.ddr \
    libccu_s5k3p9sp_mipi_raw.ddr \
    libccu_s5kgm1sp_mipi_raw.ddr \
    libccu_s5kgw1_mipi_raw.ddr \
    libccu_sala_wide_ov8856.ddr \
    libccu_salaa_qtech_main_s5kgm1sp.ddr \
    libccu_sarter_qtech_main_s5kgm1sp.ddr
